const TABLE_DATA=[
        {
            id:1,
            position:'OFF',
            x:1,
            y:1
        },
        {
            id:2,
            position:'OFF',
            x:1,
            y:2
        },
        {
            id:3,
            position:'OFF',
            x:1,
            y:3
        },
        {
            id:4,
            position:'OFF',
            x:1,
            y:4
        },
        {
            id:5,
            position:'OFF',
            x:2,
            y:1
        },

        {
            id:6,
            position:'OFF',
            x:2,
            y:2
        },

        {
            id:7,
            position:'OFF',
            x:2,
            y:3
        },
        {
            id:8,
            position:'OFF',
            x:2,
            y:4
        },
        {
            id:9,
            position:'OFF',
            x:3,
            y:1
        },
        {
            id:10,
            position:'OFF',
            x:3,
            y:2
        },
        {
            id:11,
            position:'OFF',
            x:3,
            y:3
        },
        {
            id:12,
            position:'OFF',
            x:3,
            y:4
        },
        {
            id:13,
            position:'OFF',
            x:4,
            y:1
        },
        {
            id:14,
            position:'OFF',
            x:4,
            y:2
        },
        {
            id:15,
            position:'OFF',
            x:4,
            y:3
        },
        {
            id:16,
            position:'OFF',
            x:4,
            y:4
        },

]


export default TABLE_DATA